# Generated by Django 4.1.2 on 2022-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collagename',
            name='Cid',
        ),
        migrations.AddField(
            model_name='collagename',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='collagename',
            name='collage_website',
            field=models.CharField(default='avbc', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagename',
            name='cs_cutoff',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagename',
            name='ecs_cutoff',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagename',
            name='extc_cutoff',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collagename',
            name='mech_cutoff',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Collageinfo',
        ),
    ]
